package vistasfacebook;

import java.text.SimpleDateFormat;

/**
 *
 * Instituto Tecnológico de Sonora
 *
 * @author Giovanni Garrido ID 228724
 */
public class Registro extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Registro() {
        initComponents();
    }

    SimpleDateFormat dateFormat = new SimpleDateFormat("E dd/MM/yyyy");

    /*
    
    fila[2] = dateFormat.format(venta.getFecha().getTimeInMillis());
     */
 /*
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnIniciarSesion = new javax.swing.JButton();
        lblRegistraCon = new javax.swing.JLabel();
        dtpFechaNacimiento = new com.github.lgooddatepicker.components.DatePicker();
        lblYaCuenta = new javax.swing.JLabel();
        lblRectangulo2 = new javax.swing.JLabel();
        cmbSexo = new javax.swing.JComboBox<>();
        txtCorreoElectronico = new javax.swing.JTextField();
        lblFechaNacimiento = new javax.swing.JLabel();
        lblNumeroCelular = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        txtNumeroCelular = new javax.swing.JPasswordField();
        txtNombreUsuario = new javax.swing.JPasswordField();
        btnRegistrar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        lblNombreUsuario = new javax.swing.JLabel();
        lblCorreoElectronico = new javax.swing.JLabel();
        barra1 = new javax.swing.JLabel();
        lblRectangulo3 = new javax.swing.JLabel();
        lblRectangulo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Faceboot");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(1024, 640));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnIniciarSesion.setBackground(new java.awt.Color(37, 161, 142));
        btnIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciarSesion.setText("Iniciar Sesión");
        btnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarSesionActionPerformed(evt);
            }
        });
        jPanel1.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 220, 180, 35));

        lblRegistraCon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblRegistraCon.setText("Regsitra con...");
        jPanel1.add(lblRegistraCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 390, -1, -1));
        jPanel1.add(dtpFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 450, 210, 35));

        lblYaCuenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblYaCuenta.setText("¿Ya tienes una cuenta?");
        jPanel1.add(lblYaCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, -1, -1));

        lblRectangulo2.setBackground(new java.awt.Color(159, 255, 203));
        lblRectangulo2.setOpaque(true);
        lblRectangulo2.setPreferredSize(new java.awt.Dimension(828, 16));
        jPanel1.add(lblRectangulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 320, 180));

        cmbSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maculino", "Femenino" }));
        cmbSexo.setSelectedIndex(-1);
        cmbSexo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSexoActionPerformed(evt);
            }
        });
        jPanel1.add(cmbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 370, 120, 35));

        txtCorreoElectronico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoElectronicoActionPerformed(evt);
            }
        });
        jPanel1.add(txtCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 290, 35));

        lblFechaNacimiento.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblFechaNacimiento.setText("Fecha de Nacimiento:");
        jPanel1.add(lblFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 450, -1, -1));

        lblNumeroCelular.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblNumeroCelular.setText("Número Celular:");
        jPanel1.add(lblNumeroCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 310, -1, -1));

        lblSexo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblSexo.setText("Sexo:");
        jPanel1.add(lblSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 380, -1, -1));

        txtNumeroCelular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumeroCelularActionPerformed(evt);
            }
        });
        jPanel1.add(txtNumeroCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 290, 35));

        txtNombreUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 290, 35));

        btnRegistrar.setBackground(new java.awt.Color(37, 161, 142));
        btnRegistrar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 540, 180, 35));

        btnCancelar.setBackground(new java.awt.Color(37, 161, 142));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 540, 180, 35));

        lblNombreUsuario.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblNombreUsuario.setText("Nombre de Usuario:");
        jPanel1.add(lblNombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 240, -1, -1));

        lblCorreoElectronico.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblCorreoElectronico.setText("Correo Electrónico:");
        jPanel1.add(lblCorreoElectronico, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 170, -1, -1));

        barra1.setBackground(new java.awt.Color(37, 161, 142));
        barra1.setForeground(new java.awt.Color(37, 161, 142));
        barra1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        barra1.setText("   ");
        barra1.setOpaque(true);
        jPanel1.add(barra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 65));

        lblRectangulo3.setBackground(new java.awt.Color(159, 255, 203));
        lblRectangulo3.setOpaque(true);
        lblRectangulo3.setPreferredSize(new java.awt.Dimension(828, 16));
        jPanel1.add(lblRectangulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 350, 320, 250));

        lblRectangulo1.setBackground(new java.awt.Color(159, 255, 203));
        lblRectangulo1.setOpaque(true);
        lblRectangulo1.setPreferredSize(new java.awt.Dimension(828, 16));
        jPanel1.add(lblRectangulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 510, 490));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtNombreUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreUsuarioActionPerformed

    private void txtCorreoElectronicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoElectronicoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoElectronicoActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtNumeroCelularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumeroCelularActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumeroCelularActionPerformed

    private void cmbSexoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSexoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbSexoActionPerformed

    private void btnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarSesionActionPerformed
        abrirLogin();
        dispose();
    }//GEN-LAST:event_btnIniciarSesionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barra1;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbSexo;
    private com.github.lgooddatepicker.components.DatePicker dtpFechaNacimiento;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCorreoElectronico;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblNombreUsuario;
    private javax.swing.JLabel lblNumeroCelular;
    private javax.swing.JLabel lblRectangulo1;
    private javax.swing.JLabel lblRectangulo2;
    private javax.swing.JLabel lblRectangulo3;
    private javax.swing.JLabel lblRegistraCon;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblYaCuenta;
    private javax.swing.JTextField txtCorreoElectronico;
    private javax.swing.JPasswordField txtNombreUsuario;
    private javax.swing.JPasswordField txtNumeroCelular;
    // End of variables declaration//GEN-END:variables

    private void abrirPerfil() {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perfil().setVisible(true);
            }
        });
    }

    private void abrirLogin() {

        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }
}
