/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vistasfacebook;

import comVista.IComunicadorVista;
import entidades.Usuario;
import enumeradores.Sexo;
import events.ManejadorEventos;
import events.RegistrarUsuarioEvent;
import interfaces.IRegistrarUsuarioObserver;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import peticiones.PeticionUsuario;
import utils.ConversorLocalDateToCalendar;

/**
 *
 * @author tonyd
 */
public class Registro extends javax.swing.JFrame implements IRegistrarUsuarioObserver {

    private IComunicadorVista comunicadorVista;

    /**
     * Creates new form Registro
     */
    public Registro(IComunicadorVista comunicadorVista) {
        initComponents();
        llenarComboBoxSexo();
        this.comunicadorVista = comunicadorVista;
        
        RegistrarUsuarioEvent.getInstance().suscribirse(this);
        //suscribeRegistrarComentario(this);
        //suscribeRegistrarPublicacion(this);
    }

    public void llenarComboBoxSexo(){
        cbSexo.setModel(new DefaultComboBoxModel(Sexo.values()));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNoCelular = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        lblFechaNacimiento = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblRegistraCon = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        lblYaTienesCuenta = new javax.swing.JLabel();
        lblIcoFacebbok = new javax.swing.JLabel();
        lblIcoGoogle = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        txtNoCelular = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtFechaNacimiento = new com.github.lgooddatepicker.components.DatePicker();
        cbSexo = new javax.swing.JComboBox<>();
        btnAgregar = new javax.swing.JButton();
        btnIniciarSesion = new javax.swing.JButton();
        btnCancelar1 = new javax.swing.JButton();
        btnEntraFacebook = new javax.swing.JButton();
        btnEntraGoogle = new javax.swing.JButton();
        barra1 = new javax.swing.JLabel();
        barra2 = new javax.swing.JLabel();
        rectangulo1 = new javax.swing.JLabel();
        rectangulo2 = new javax.swing.JLabel();
        rectangulo3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login Faceboot");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setForeground(new java.awt.Color(153, 153, 153));
        jPanel1.setMinimumSize(new java.awt.Dimension(910, 600));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNoCelular.setText("No. Celular");
        lblNoCelular.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jPanel1.add(lblNoCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(143, 270, -1, -1));

        lblPassword.setText("Contraseña");
        lblPassword.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jPanel1.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(145, 220, -1, -1));

        lblFechaNacimiento.setText("Fecha de nacimiento");
        lblFechaNacimiento.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jPanel1.add(lblFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 370, -1, -1));

        lblSexo.setText("Sexo");
        lblSexo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jPanel1.add(lblSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(192, 320, -1, -1));

        lblEmail.setText("E-mail");
        lblEmail.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jPanel1.add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        lblRegistraCon.setText("Registra con...");
        lblRegistraCon.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(lblRegistraCon, new org.netbeans.lib.awtextra.AbsoluteConstraints(658, 300, -1, -1));

        lblNombre1.setText("Nombre");
        lblNombre1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jPanel1.add(lblNombre1, new org.netbeans.lib.awtextra.AbsoluteConstraints(167, 120, -1, -1));

        lblYaTienesCuenta.setText("¿Ya tienes una cuenta?");
        lblYaTienesCuenta.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jPanel1.add(lblYaTienesCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(623, 140, -1, -1));
        jPanel1.add(lblIcoFacebbok, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 353, -1, -1));
        jPanel1.add(lblIcoGoogle, new org.netbeans.lib.awtextra.AbsoluteConstraints(605, 424, -1, -1));

        txtEmail.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, 240, -1));

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, 240, -1));

        txtNoCelular.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(txtNoCelular, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, 240, -1));

        txtNombre.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreActionPerformed(evt);
            }
        });
        jPanel1.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 240, -1));
        jPanel1.add(txtFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 370, 250, -1));

        cbSexo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        cbSexo.setToolTipText("");
        jPanel1.add(cbSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 130, -1));

        btnAgregar.setText("Registrar");
        btnAgregar.setBackground(new java.awt.Color(37, 161, 142));
        btnAgregar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 430, 180, 35));

        btnIniciarSesion.setText("Iniciar Sesión");
        btnIniciarSesion.setBackground(new java.awt.Color(37, 161, 142));
        btnIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnIniciarSesion.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(btnIniciarSesion, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 190, 180, 35));

        btnCancelar1.setText("Cancelar");
        btnCancelar1.setBackground(new java.awt.Color(37, 161, 142));
        btnCancelar1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCancelar1.setForeground(new java.awt.Color(255, 255, 255));
        btnCancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelar1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnCancelar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 180, 35));

        btnEntraFacebook.setText("Entra con FaceBook");
        btnEntraFacebook.setBackground(new java.awt.Color(59, 89, 152));
        btnEntraFacebook.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnEntraFacebook.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(btnEntraFacebook, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 270, 35));

        btnEntraGoogle.setText("Entra con Google");
        btnEntraGoogle.setBackground(new java.awt.Color(219, 74, 57));
        btnEntraGoogle.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btnEntraGoogle.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(btnEntraGoogle, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 420, 270, 35));

        barra1.setBackground(new java.awt.Color(37, 161, 142));
        barra1.setOpaque(true);
        jPanel1.add(barra1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 910, 60));

        barra2.setBackground(new java.awt.Color(37, 161, 142));
        barra2.setOpaque(true);
        jPanel1.add(barra2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 60));

        rectangulo1.setBackground(new java.awt.Color(159, 255, 203));
        rectangulo1.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        rectangulo1.setOpaque(true);
        jPanel1.add(rectangulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 500, 400));

        rectangulo2.setBackground(new java.awt.Color(159, 255, 203));
        rectangulo2.setOpaque(true);
        jPanel1.add(rectangulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 275, 320, 220));

        rectangulo3.setBackground(new java.awt.Color(159, 255, 203));
        rectangulo3.setOpaque(true);
        jPanel1.add(rectangulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, 320, 150));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String nombre = this.txtNombre.getText();
        String password = String.valueOf(this.txtPassword.getPassword());
        String email = this.txtEmail.getText();
        String telefono = this.txtNoCelular.getText();
        Sexo sexo = (Sexo) cbSexo.getSelectedItem();
        Calendar fechaNacimiento = ConversorLocalDateToCalendar.convertir(this.txtFechaNacimiento.getDate());
        Usuario usuario = new Usuario(nombre, password, email, telefono, sexo, fechaNacimiento);
        comunicadorVista.registrarUsuario(usuario);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnCancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelar1ActionPerformed
        this.dispose();
        RegistrarUsuarioEvent.getInstance().desuscribirse(this);
        Login login = new Login(comunicadorVista);
        login.setVisible(true);
    }//GEN-LAST:event_btnCancelar1ActionPerformed

    @Override
    public void onRegistrarUsuario(PeticionUsuario peticionUsuario) {
        if(peticionUsuario.getStatus() >= 400){
            JOptionPane.showMessageDialog(this, peticionUsuario.getMensajeError(), "Aviso", JOptionPane.INFORMATION_MESSAGE);
        } else{
            JOptionPane.showMessageDialog(this, "El usuario se registro correctamente", "Aviso", JOptionPane.INFORMATION_MESSAGE);
        }
    }
  
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Registro().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel barra1;
    private javax.swing.JLabel barra2;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnCancelar1;
    private javax.swing.JButton btnEntraFacebook;
    private javax.swing.JButton btnEntraGoogle;
    private javax.swing.JButton btnIniciarSesion;
    private javax.swing.JComboBox<String> cbSexo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFechaNacimiento;
    private javax.swing.JLabel lblIcoFacebbok;
    private javax.swing.JLabel lblIcoGoogle;
    private javax.swing.JLabel lblNoCelular;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblRegistraCon;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblYaTienesCuenta;
    private javax.swing.JLabel rectangulo1;
    private javax.swing.JLabel rectangulo2;
    private javax.swing.JLabel rectangulo3;
    private javax.swing.JTextField txtEmail;
    private com.github.lgooddatepicker.components.DatePicker txtFechaNacimiento;
    private javax.swing.JTextField txtNoCelular;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables

    
}
